/**
 * Safely parses an ISO date string, normalizing naive UTC datetimes (generated by Python)
 * by appending the 'Z' timezone designator if no offset is present.
 */
export const parseISOToDate = (isoString: string | null | undefined): Date | null => {
  if (!isoString) return null;
  // If the string doesn't end with Z or a timezone offset like +00:00 or -05:00, treat it as UTC by appending 'Z'
  const normalized = (isoString && !isoString.endsWith('Z') && !/[+-]\d{2}:\d{2}$/.test(isoString))
    ? `${isoString}Z`
    : isoString;
  const date = new Date(normalized);
  return isNaN(date.getTime()) ? null : date;
};

/**
 * Formats a Date object or ISO string to a localized date & time string.
 */
export const formatLocalDateTime = (isoString: string | null | undefined): string => {
  const date = parseISOToDate(isoString);
  if (!date) return 'Never';
  return date.toLocaleDateString() + ' ' + date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
};

/**
 * Formats a Date object or ISO string to a localized date & time string with seconds.
 */
export const formatLocalDateTimeWithSeconds = (isoString: string | null | undefined): string => {
  const date = parseISOToDate(isoString);
  if (!date) return 'Never';
  return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) + 
         ' (' + date.toLocaleDateString() + ')';
};

/**
 * Formats a Date object or ISO string to a localized time string.
 */
export const formatLocalTimeOnly = (isoString: string | null | undefined): string => {
  const date = parseISOToDate(isoString);
  if (!date) return 'Recent';
  return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
};
